### ISSUE TITLE
✨ Feature: Add PR validation workflow with lint and build checks

### ISSUE THREAD

**Issue by smithshiro** [smithshiro/smithshiro.github.io#6]
## 📋 概要
Pull Request作成時に自動的にlintエラーやビルドエラーを検知できるGitHub Actions ワークフローを追加したいです。

## 🎯 目的
- PR作成/更新時の自動品質チェック
- マージ前のエラー早期発見
- コードの品質維持
- 開発体験の向上

### 1. PR用ワークフロー
- **トリガー**: PR作成・更新時
- **チェック項目**:
  - ESLint実行
  - TypeScript型チェック  
  - Next.jsビルドテスト
  - 依存関係の整合性確認

### 2. ステータスチェック
- PRページでチェック結果を表示
- ❌ エラーがある場合はマージをブロック
- ✅ 全チェック通過でマージ許可

### 3. 詳細レポート
- エラー詳細をPRコメントで表示
- 修正提案があれば表示

## 📚 参考実装
```yaml
name: PR Validation
on:
  pull_request:
    branches: [main]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
      - name: Type check
        run: npm run type-check  
      - name: Build test
        run: npm run build
```

## ✅ 期待される効果
- 🚀 デプロイエラーの事前防止
- 🔍 コード品質の自動チェック
- ⚡ 開発フローの改善
- 🛡️ mainブランチの安定性確保

## 📋 実装予定
1. `.github/workflows/pr-validation.yml` 作成
2. package.jsonにlint/type-checkスクリプト追加
3. ブランチ保護ルール設定（オプション）
4. 動作テスト

Priority: High
Labels: enhancement, ci/cd, workflow
